
name: Contexts actions

on: workflow_dispatch
jobs:
    Deploy:
        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
            - name: deploy prd
              run: echo "Deployment prd server on branch $GITHUB_REF"  
            - name: context github
              env:
                GITHUB_CONTEXT: ${{ toJson(github)}}
              run: echo "$GITHUB_CONTEXT"
            
            - name: Dump job context
              env:
                JOB_CONTEXT: ${{ toJson(job)}}
              run: echo "$JOB_CONTEXT"