name: Docker workflow

on: 
  schedule:
    - cron: "*/1 * * * *"

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: nginx
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME
            
            - name: Docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            