
name: Multi-job generate ascii cowsay

on: [push]

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu repo
        run: sudo apt-get update -y
      
      - name: Install cowsay
        run: sudo apt install cowsay -y
    
      - name: Execute cowsay 
        run: cowsay -f dragon "Run for cover, I am a DRAGON.........RAWR" >> dragon.txt

      - name: Sleep 30s
        run: sleep 30
    
  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 10s
        run: sleep 10

      - name: validate dragon
        run: grep -i "dragon" dragon.txt
  
  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt
    