name: Workflow activities

on:
 workflow_dispatch: 
 push:
    branches: 
        - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is workflow executed for event type - ${{ github.event_name }}"
