
name: Contexts actions

on: workflow_dispatch
jobs:
    Deploy:
        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3
        - run: |
            echo Terraform deploy
            terraform version
            echo terraform init
            terraform init
            terraform validate
            terraform fmt
            terraform plan
           
