name: Workflow activities

on:
 workflow_dispatch: 
 push:
    branches: 
        - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v
            
            - name: Terraform version
              run: terraform version
            
            