name: Workflow activities

on:
 workflow_dispatch: 
 push:
    branches: 
        - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Setup Terraform

              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.7 

            
            