name: Workflow activities

on:
 workflow_dispatch: 
 push:
    branches: 
        - master

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Validate event name and branch deploy
              run: echo "This is workflow executed for event type - ${{ github.event_name }} ${{ github.ref }}"
            
            - name: Terraform version
              run: terraform version
            
            